### ISSUE TITLE
Consider removing --hostname-override kubelet flag (requires k0smotron bump to v1.0.2)

### ISSUE THREAD

**Issue by DinaBelova** [Mirantis/hmc#136]
k0smotron recently released the new version v1.0.2 that contains the fix for https://github.com/k0sproject/k0smotron/pull/646 thus AWS deployments should work without the _--hostname-override_ flag now. _--hostname-override_ flag was initially set because the hostname set by default does not equal the node name which breaks the AWS CCM. But according to the information from the k0smotron team the _--hostname-override_ flag may now break scaling and control-plane upgrades.

We should check if AWS deployments work without this flag with v1.0.2 k0smotron.

**Comment by eromanova** [comment]
Testing discovered: https://github.com/k0sproject/k0smotron/issues/665
