### ISSUE TITLE
managed-by annotation in hosted-cp deployment prevents workers creation

### ISSUE THREAD

**Issue by DinaBelova** [Mirantis/hmc#143]
We use the _cluster.x-k8s.io/managed-by: k0smotron_ annotation in our _aws-hosted-cp_ deployment. 

This is advised by k0smotron deployment guide here: https://docs.k0smotron.io/v1.0.2/capi-aws/

Where it’s explicitly said that _This marks the base infra to be self managed. The value of the annotation is irrelevant, as long as there is a value._ 

In CAPI docs https://cluster-api.sigs.k8s.io/reference/labels_and_annotations this annotation is explained as _that some external system is managing the cluster infrastructure_. In this case this means that k0smotron should be responsible for AWS resources creation, which it doesn’t.

And Cluster API AWS provider just skipping reconcile and creation of all AWS resources (including workers).

This behavior makes no sense, since it implies that users should provision all AWS infrastructure (including workers) for k0smotron by themselves.

**Comment by a13x5** [comment]
The discussion is moved to k0sproject/k0smotron#668

**Comment by DinaBelova** [comment]
Closing per @a13x5 comment
