### ISSUE TITLE
Consider splitting up internal Templates and Cluster Templates in different folders or even different CDS

### ISSUE THREAD

**Issue by DinaBelova** [Mirantis/hmc#149]
While @Schnitzel was going through current hmc implementation - he was very confused about the fact that there are Templates also for “internal” things like _cluster-api_ or _hmc_ which there are also templates for Cluster deployments like aws-hosted-cp:

> While I think it’s extremely cool and offers a lot of flexibility to use the Template capability to not only deploy clusters but also to bootstrap HMC and the components itself, I’m concerned that this could cause confusion, some examples:
> 
> - running a kubectl list templates will not only show Cluster Templates but also internal Templates to a platform engineer, which could cause some confusion.
> - As the leader of the platform engineers I might want to restrict my team of platform engineers which templates are allowed to be used, so I might delete the Template Objects I don’t want them to use (or create my own). But if the internal components also use Template Objects and I remove them, then I might not be able to upgrade HMC in the future or I destroy it all together
> 
> Based on that I wonder if we should separate the Templates used for different functions? Maybe keep the Template Object for actual Cluster Deployment Templates, but create a new CRD Component or similar for internal components?

Let's keep this issue open until further discussions.

**Comment by eromanova** [comment]
Templates were split into multiple types in #287. This can be closed.
