### ISSUE TITLE
Standalone controlplane template for Azure

### ISSUE THREAD

**Issue by Kshatrix** [Mirantis/hmc#205]

**Comment by a13x5** [comment]
Template is ready, but CCM and CSI will not function properly due to k0sproject/k0smotron#692

Workaround (if it's possible) should be discussed separately.

**Comment by DinaBelova** [comment]
@a13x5 can you please
- check w/ k0smotron dev team when the issues is expected to be fixed

Note: I've add the relevant k0smotron issue to the list that we track
