### ISSUE TITLE
[Admission] Forbid to remove the Template object if one or more ManagedCluster references it

### ISSUE THREAD

**Issue by eromanova** [Mirantis/hmc#246]

**Comment by slysunkin** [comment]
I'd like to clarify a few details.

We have the following hierarchy:
for AWS
```
MachineDeployment
  - K0sWorkerConfigTemplate
  - AWSMachineTemplate
```

for Azure
```
MachineDeployment
  - K0sWorkerConfigTemplate
  - AzureMachineTemplate
```

So, we need to wait for MachineDeployment termination before K0sWorkerConfigTemplate, AWSMachineTemplate/AzureMachineTemplate (respectively to provider type).

**Comment by eromanova** [comment]
@slysunkin It will be enough to check the `ManagedCluster` existence that references (`spec.template`) the Template that was triggered for the removal and forbid it if at least one `ManagedCluster` is found. Similarly, it's currently done for Management object removal: https://github.com/Mirantis/hmc/blob/main/internal/webhook/management_webhook.go#L65 No need to check internal cluster objects.
