### ISSUE TITLE
Proposal: Set Up MkDocs for Structured Documentation Site

### ISSUE THREAD

**Issue by jlnhnng** [Mirantis/hmc#275]
Currently, the project uses markdown files for documentation (docs/ directory), but there is no organized structure or tool to create a documentation site. By using MkDocs, we can turn the existing markdown files into a user-friendly, searchable, and structured documentation site.

**Problem**:
The current approach of having plain markdown files in the docs/ directory makes it difficult to navigate or view documentation in an organized manner. Users don’t get the benefits of a professional documentation system (like search functionality or a table of contents) when browsing through GitHub.

**Proposed Solution**:
- Integrate MkDocs: Use MkDocs to convert markdown files into an organized static documentation site.
- Material Theme: Utilize the Material theme for a modern look and feel.
- Makefile Commands: Add Makefile targets for serving, building, and deploying the documentation.
- GitHub Pages for Deployment: Deploy the documentation to GitHub Pages for easy access and versioning.

Once this feature is set up, the project will benefit from a well-organized, easy-to-navigate documentation site with search functionality and a modern look, improving the user experience for both developers and users of the HMC project.

**Next Steps**:
If this solution is accepted, I can create a PR to implement it, including the necessary configuration and Makefile changes.

**Comment by z3t444** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by p5ntangle** [comment]
I think this would be a great way to get us started and help encourage more people to contribute to the docs. It would be great for us to add this.

**Comment by Schnitzel** [comment]
we discussed this as a team and decided to implement this, its being tracked here https://github.com/Mirantis/hmc/issues/335
