### ISSUE TITLE
Setup a dedicated documentation repo for 2A

### ISSUE THREAD

**Issue by p5ntangle** [Mirantis/hmc#367]
Given the broader scope of HMC as part of Project 2A it make sense to move the docs into its own repo with dedicated reviews and actions.

**Comment by Schnitzel** [comment]
+1 from my side, /cc @PrashantR30

**Comment by p5ntangle** [comment]
i have created the new repo and will do the pull request to remove the docs from the current repo.

**Comment by PrashantR30** [comment]
> i have created the new repo and will do the pull request to remove the docs from the current repo.
I have the git commit to remove the docs from the current repo, I just need permission to push and we review and merge.
