### ISSUE TITLE
Investigate an issue with VPC deletion

### ISSUE THREAD

**Issue by slysunkin** [Mirantis/hmc#470]
Issue with cluster deletion: VPC can't be deleted because of the VPC Interface endpoints. The endpoints are used by the EKS for communication, so it looks like a bug in CAPA, since these endpoints look unmanaged.

**Comment by slysunkin** [comment]
The cause of the bug can be the same as we fixed with AWSCluster/Machine finalizers (https://github.com/Mirantis/hmc/issues/217)

**Comment by slysunkin** [comment]
Investigating the process of removal the control plane:
`k describe AWSManagedControlPlane eks-dev-slava-14-cp -n hmc-system`
discovered these messages:
```
  Normal   SuccessfulDeleteEKSCluster        26m  aws-controller  Deleted EKS Cluster hmc-system_eks-dev-slava-14-cp
  Normal   SuccessfulDeleteSecurityGroup     26m  aws-controller  Deleted cluster managed SecurityGroup "sg-0bfc9b15c6f45fe42"
  Normal   SuccessfulDisassociateRouteTable  26m  aws-controller  Disassociated managed RouteTable "rtb-0c11f339e13d2dcdd" from subnet "subnet-0c3932f4c41af37e1"
  Normal   SuccessfulDeleteRouteTable        26m  aws-controller  Deleted managed RouteTable "rtb-0c11f339e13d2dcdd"
  Normal   SuccessfulDisassociateRouteTable  26m  aws-controller  Disassociated managed RouteTable "rtb-06e62cdd483b7b37d" from subnet "subnet-047a351e31211afc1"
  Normal   SuccessfulDeleteRouteTable        26m  aws-controller  Deleted managed RouteTable "rtb-06e62cdd483b7b37d"
  Normal   SuccessfulDisassociateRouteTable  26m  aws-controller  Disassociated managed RouteTable "rtb-01dc8d0ed98558e75" from subnet "subnet-042f8dd2a5f76781a"
  Normal   SuccessfulDeleteRouteTable        26m  aws-controller  Deleted managed RouteTable "rtb-01dc8d0ed98558e75"
  Normal   SuccessfulDisassociateRouteTable  26m  aws-controller  Disassociated managed RouteTable "rtb-0ea1440ffa4b40a23" from subnet "subnet-036136b1b16dcd4d1"
  Normal   SuccessfulDeleteRouteTable        26m  aws-controller  Deleted managed RouteTable "rtb-0ea1440ffa4b40a23"
  Normal   SuccessfulDisassociateRouteTable  26m  aws-controller  Disassociated managed RouteTable "rtb-02b074d4db4ff4f89" from subnet "subnet-051ba44b89b0b0db8"
  Normal   SuccessfulDeleteRouteTable        26m  aws-controller  Deleted managed RouteTable "rtb-02b074d4db4ff4f89"
  Normal   SuccessfulDisassociateRouteTable  26m  aws-controller  Disassociated managed RouteTable "rtb-047a2a339dec488f5" from subnet "subnet-078b08ee3a55db9a8"
  Normal   SuccessfulDeleteRouteTable        26m  aws-controller  Deleted managed RouteTable "rtb-047a2a339dec488f5"
  Normal   SuccessfulDeleteNATGateway        26m  aws-controller  Deleted NAT Gateway "nat-070f4b940ef366695" previously attached to VPC "vpc-01910d574b9ba221d"
  Normal   SuccessfulDeleteNATGateway        26m  aws-controller  Deleted NAT Gateway "nat-039f6acd381cefc92" previously attached to VPC "vpc-01910d574b9ba221d"
  Normal   SuccessfulDeleteNATGateway        26m  aws-controller  Deleted NAT Gateway "nat-03fc12dc502489202" previously attached to VPC "vpc-01910d574b9ba221d"
  Normal   SuccessfulDetachInternetGateway   25m  aws-controller  Detached Internet Gateway "igw-09becef7ddc7c6353" from VPC "vpc-01910d574b9ba221d"
  Normal   SuccessfulDeleteInternetGateway   25m  aws-controller  Deleted Internet Gateway "igw-09becef7ddc7c6353" previously attached to VPC "vpc-01910d574b9ba221d"
  Warning  FailedDeleteSubnet                25m  aws-controller  Failed to delete managed Subnet "subnet-042f8dd2a5f76781a": DependencyViolation: The subnet 'subnet-042f8dd2a5f76781a' has dependencies and cannot be deleted.
           status code: 400, request id: d85e10dd-6997-4b6f-be79-13e2b8b2c976
  Warning  FailedDeleteSubnet  25m  aws-controller  Failed to delete managed Subnet "subnet-042f8dd2a5f76781a": DependencyViolation: The subnet 'subnet-042f8dd2a5f76781a' has dependencies and cannot be deleted.
           status code: 400, request id: 644580c9-4cdd-46ea-9d98-023b595ce29a
  Warning  FailedDeleteSubnet  25m  aws-controller  Failed to delete managed Subnet "subnet-042f8dd2a5f76781a": DependencyViolation: The subnet 'subnet-042f8dd2a5f76781a' has dependencies and cannot be deleted.
           status code: 400, request id: 7fd6235e-dc2d-491e-9e74-5106f1b80db6
  Warning  FailedDeleteSubnet  25m  aws-controller  Failed to delete managed Subnet "subnet-042f8dd2a5f76781a": DependencyViolation: The subnet 'subnet-042f8dd2a5f76781a' has dependencies and cannot be deleted.
           status code: 400, request id: e2a7b45d-55e7-446f-bb12-ea4f14861e8b
  Warning  FailedDeleteSubnet  24m  aws-controller  Failed to delete managed Subnet "subnet-042f8dd2a5f76781a": DependencyViolation: The subnet 'subnet-042f8dd2a5f76781a' has dependencies and cannot be deleted.
           status code: 400, request id: db4eeb21-d466-47ee-a343-779b3bddc1e7
  Warning  FailedDeleteSubnet  24m  aws-controller  Failed to delete managed Subnet "subnet-042f8dd2a5f76781a": DependencyViolation: The subnet 'subnet-042f8dd2a5f76781a' has dependencies and cannot be deleted.
           status code: 400, request id: 563d9c5c-7f75-4682-b722-7144fda4d1d5
  Warning  FailedDeleteSubnet  24m  aws-controller  Failed to delete managed Subnet "subnet-042f8dd2a5f76781a": DependencyViolation: The subnet 'subnet-042f8dd2a5f76781a' has dependencies and cannot be deleted.
           status code: 400, request id: 73921edf-be53-4792-b9c6-3f379e6fc23b
  Warning  FailedDeleteSubnet  24m  aws-controller  Failed to delete managed Subnet "subnet-042f8dd2a5f76781a": DependencyViolation: The subnet 'subnet-042f8dd2a5f76781a' has dependencies and cannot be deleted.
           status code: 400, request id: 58b007f8-ee9f-4dff-92f4-585aa9d4dedb
  Warning  FailedDeleteSubnet  24m  aws-controller  Failed to delete managed Subnet "subnet-042f8dd2a5f76781a": DependencyViolation: The subnet 'subnet-042f8dd2a5f76781a' has dependencies and cannot be deleted.
           status code: 400, request id: cab174f1-3468-4cfd-8db8-6f895f86085f
  Warning  FailedDeleteSubnet  86s (x779 over 24m)  aws-controller  (combined from similar events): Failed to delete managed Subnet "subnet-042f8dd2a5f76781a": DependencyViolation: The subnet 'subnet-042f8dd2a5f76781a' has dependencies and cannot be deleted.
           status code: 400, request id: a64e80b4-7c92-4662-ada9-851427d121b0
  Warning  FailedDeleteSubnet  86s (x779 over 24m)  aws-controller  (combined from similar events): Failed to delete managed Subnet "subnet-042f8dd2a5f76781a": DependencyViolation: The subnet 'subnet-042f8dd2a5f76781a' has dependencies and cannot be deleted.
           status code: 400, request id: a64e80b4-7c92-4662-ada9-851427d121b0
```
This is the cause of the problem with VPC deletion.

**Comment by slysunkin** [comment]
Created a bug report: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/5150

**Comment by slysunkin** [comment]
More investigations demonstrated that deletion of VPC may be quite problematic. It may be caused by Amazon infrastructure and delays in their garbage collection. Sometimes VPC can be deleted by `aws-nuke` (by making more retries), but in some situations `aws-nuke` shows this after 30 retries:
```
┌────────────────────────────────────────────────────────────────────────────────────────┐
| Identifier               | Resource Type | Deleted Successfully                        |
| subnet-0bba42de2de2219a2 | Subnet        | ❌ DependencyViolation: The subnet 'subnet- |
| -------------------------------------------------------------------------------------- |
| subnet-01bcb1bcf457de8fe | Subnet        | ❌ DependencyViolation: The subnet 'subnet- |
| -------------------------------------------------------------------------------------- |
| vpc-0904283dda6216f67    | VPC           | ❌ 'Waiting for all Network interfaces to b |
| -------------------------------------------------------------------------------------- |
| subnet-09449bf09e07c6028 | Subnet        | ❌ DependencyViolation: The subnet 'subnet- |
└────────────────────────────────────────────────────────────────────────────────────────┘
```
and resources can be freed a couple of hours later.

**Comment by slysunkin** [comment]
It looks like current resource de-allocation procedure is working like this:
1. take the first child item
2. if removal fails, wait 10 seconds
3. go to step 1

When I removed manually VPC and its child items I did this:
1. take the first child item
2. if removal fails, go to the next child item
3. request to remove it
4. if removal fails, go to the next child item
...
5. go to the VPC and try to remove it
6. if fails go to step 1

So, probably it should be re-written as something like this manual algorithm.

**Comment by DinaBelova** [comment]
looks like will depend on the upstream fix, will close in our project for now

**Comment by s3rj1k** [comment]
After some investigation the AWS EKS documentation hinted that this is not a bug but an expected platform implementation/behavior or a quirk.

Documentation regarding EKS cluster deletion https://docs.aws.amazon.com/eks/latest/userguide/delete-cluster.html states that for a proper Cluster deletion one should manually remove related objects before actual deletion or use `eksctl` CLI utility to somewhat automate deletion. Note that `eksctl` is a Golang CLI.

Creating a cluster with default HMC flow and when deleting it using `eksctl` makes overall deletion succeed, but some dangling objects like VPCE remain and they need to be nuked via a combination of cloudnuke and manual deletion via console, however, note that cluster deletion succeeded.

In case of cluster creation and deletion via `eksctl` everything gets deleted correctly yet dangling objects like VPC(E) are left to manual cleanup also.

Documentation for cluster creation states that one should specify existing VPCs for reuse purposes or when not specified they would be created by `eksctl`.

Example command to create cluster using `eksctl`:
```
eksctl create cluster \
	--name eks-dev \
	--region us-east-2 \
	--version 1.31 \
	--without-nodegroup
```

Example command to delete cluster using `eksctl`:
```
eksctl delete cluster --name eks-dev
```

In addition there is network requirements described here: https://docs.aws.amazon.com/eks/latest/userguide/network-reqs.html#network-requirements-subnets 

Related code paths for deletion:
https://github.com/eksctl-io/eksctl/blob/main/pkg/actions/cluster/unowned.go#L58
https://github.com/eksctl-io/eksctl/blob/main/pkg/actions/cluster/owned.go#L72

Owned vs UnOwned:
https://github.com/eksctl-io/eksctl/blob/main/pkg/actions/cluster/cluster.go#L39
https://github.com/eksctl-io/eksctl/blob/main/pkg/actions/cluster/cluster.go#L47

Essentially `owned` deletion code path is taken when the cluster was created by `eksctl` and UnOwned for any other (adopted) cluster.

**Comment by s3rj1k** [comment]
Additional findings:
 - GuardDuty created `Security Groups` are blocking VPC deletion due to being linked to VPC that is owned by Cluster but SG itself is not owned (`sigs.k8s.io/cluster-api-provider-aws/cluster/eks-dev` tag) so CAPA by-design can't do anything about that
 - Suggestion to add `additionalTags` in AWSManagedControlPlane like [here](https://github.com/Mirantis/hmc/commit/a34e06d3c23588857b4840d013c523ce4fdd9ace) this will ensure presence of NameAWSProviderOwned tag in objects created by CAPA (not all of them for some reason set this tag automatically)
 - VPC deletion in CAPA is blocked [here](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/network/vpc.go#L284)

Above code will delete VPC for `AWSCluster` that has S3 bucket, problem is that `AWSManagedCluster`, that we use, does not have `s.scope.Bucket()` [needs additional verification]
