### ISSUE TITLE
Helm upgrade should also provide the release object

### ISSUE THREAD

**Issue by a13x5** [Mirantis/hmc#724]
_This should be discussed separately in broader scope_ 

# The issue

When using older version of hmc and running 

```bash
helm upgrade hmc oci://ghcr.io/mirantis/hmc/charts/hmc --version 0.0.4 -n hmc-system
```

The hmc controller gets updated, but new release isn't created.

# Possible solution

We should provide new release object associated with the helm release, so user can use helm upgrade workflow and skip manual download of release manifest from github,

**Comment by Kshatrix** [comment]
The upgrade process is described [here](https://github.com/Mirantis/project-2a-docs/commit/57a94add68824f657938bdf3c80c3db2dbe94449).
You shouldn't upgrade the helm release manually. The idea was to manage upgrades via Management and Release resources only

**Comment by a13x5** [comment]
Closing, since it's working as designed.
Currently there is no plans to support this scenario.
