### ISSUE TITLE
Core Beachhead ServiceTemplates for 2A

### ISSUE THREAD

**Issue by DinaBelova** [Mirantis/hmc#728]
**Goals**
Create a comprehensive set of production-ready ServiceTemplates for essential infrastructure services (beachhead services) that enable secure, compliant, and efficient multi-cluster operations
- Enable standardized deployment of critical infrastructure components across diverse cloud environments
- Reduce operational complexity through automated service lifecycle management
- Establish security and compliance baselines for enterprise infrastructure services
- Provide platform teams with validated, enterprise-grade service configurations that support scalable multi-cluster operations

**Major deliverables**
- Authentication	DEX	Unified identity and access management with flexible SSO integration, supporting 2A-IDP’s need for secure, compliant multi-cloud authentication.
- Backup and Recovery	Velero	Scalable backup and recovery solution for multi-cloud environments, aligning with 2A-IDP’s emphasis on data resilience and disaster recovery to ensure continuity in regulated environments.
- Certificate Management	 Cert Manager	Automates certificate lifecycle management to ensure secure, compliant communication across environments, aligning with 2A-IDP’s declarative infrastructure approach and supporting enterprise security at scale.
- [already implemented] Ingress Management	NGINX Ingress	Inbound traffic control, SSL termination, and routing across clusters, ensuring reliable, secure access paths for applications in 2A-IDP’s multi-cloud environments.
- [already there as part of k0s deployment] Networking	Calico**	Foundational networking and policy management for secure, multi-cluster communication across hybrid clouds, supporting 2A-IDP’s goals of operational independence and scalable, policy-driven networking without proprietary dependencies.
- [already implemented] Policy Management	Kyverno Policy	Standardized security and compliance controls across clusters, aligning with 2A-IDP’s regulatory focus and supporting scalable, compliant deployments.
- Secrets Management	External Secrets	Centralizes secret management across clouds, enabling compliant integration with systems like AWS Secrets Manager and Vault, simplifying operations and supporting 2A-IDP’s security objectives for distributed applications.What the outcome will be for your epic. 

** For GA, if we have a helm chart that is already provided by the ClusterTemplate, it will cover what is required for this epic.  We will need to invest effort in how we approach the beachhead service post-deployment by the clustertemplate.

**Who it benefits**
- Platform Lead: Standardized infrastructure services
- Platform Engineer: Automated service deployment
- Application Developer: Ready-to-use infrastructure services

**Acceptance criteria**
- All core beachhead ServiceTemplates successfully tested and validated
- Cross-cluster operations verified
- Documentation complete for each service

**Assumptions**
- Teams prefer standardized configurations
- Services work consistently across clouds
- Infrastructure capable to host the beachhead services.

**Limitations**
- Cloud provider API restrictions
- Resource requirements vary by environment
- Initial setup complexity to develop

**Out of scope**
- Custom/Bespoke service variations
- Advanced configuration options (minimal vanilla)
- Non-standard deployment patterns
- Cloud-specific optimizations or needs, validate only on current supported CAPI clusters.

**User stories**

Platform Lead:
- As a Platform Lead, I want standardized service templates so I can ensure consistency across clusters
- As a Platform Lead, I want automated service deployment so I can reduce operational overhead
- As a Platform Lead, I want security baselines so I can ensure compliance

Platform Engineer:
- As a Platform Engineer, I want automated service configuration so I can quickly deploy infrastructure
- As a Platform Engineer, I want version management so I can control service updates

Application Developer:
- As an Application Developer, I want self-service access to infrastructure so I can deploy applications
- As an Application Developer, I want consistent service interfaces so I can rely on infrastructure

**Comment by BROngineer** [comment]
@DinaBelova @mestadler 
A gap in the current concept: there is no mechanism for embedding beachhead service charts. What do I mean? The template controller works with a registry defined by a command line flag. By default it is `"oci://ghcr.io/mirantis/hmc/charts"`, however it can be overridden by the user when deploying the HMC. Therefore, a user with a custom registry will face a situation where after deployment he will have a set of service templates in a failed state.

How could we solve it? From my perspective, HMC must run local registry where all bundled service template charts will be pushed. This will guarantee, that all service charts defined by bundled templates will be available for deployment.

**Comment by DinaBelova** [comment]
this also relates to the discussion we have to have around #693
the similar internal registry need is highlighted there
