### ISSUE TITLE
observability solution verification

### ISSUE THREAD

**Issue by DinaBelova** [Mirantis/hmc#733]
Testing a multicluster setup, where multiple child and regional clusters are created and metrics aggregated from both clusters.

**Comment by gmlexx** [comment]
It generally works, some dashboard labels probably need adjustment, like [clusterName] (https://github.com/Mirantis/motel/blob/cad8649fef468de3a4aa34ae2c88e5400bbb3532/demo/demo-mothership-values.yaml#L2)
As different child clusters are distinguished by promxyCluster label, clusterName has the same value for all clusters.

**Comment by gmlexx** [comment]
Discovered a few issues:

- https://github.com/Mirantis/motel/issues/3
- https://github.com/Mirantis/motel/issues/2
