### ISSUE TITLE
Consider defining concrete errors instead of using errors.New inline

### ISSUE THREAD

**Issue by s3rj1k** [Mirantis/hmc#767]
Consider defining concrete errors instead of using errors.New inline.
Example:
`var ErrNoClusterSummary` instead of `return errors.New("...")`

**Comment by zerospiel** [comment]
Most of the errors are created in that way to reuse it in the logger and then immediately return from a method, they are sentinel but are not required to be exported or dedicated to global-level variables. `errors.New` is being used to avoid the costly `fmt.Errorf`

**Comment by s3rj1k** [comment]
```
internal/webhook/release_webhook.go:34:var errManagementIsNotFound = errors.New("no Management object found")
...
internal/sveltos/status.go:31:		return nil, errors.New("error getting status from ClusterSummary: nil summary provided")
```
