### ISSUE TITLE
Telemetry `segmentToken` should be configurable?

### ISSUE THREAD

**Issue by s3rj1k** [Mirantis/hmc#771]
`segmentToken` is always empty in telemetry, should it be configurable or feature is not finished yet?

**Comment by s3rj1k** [comment]
also note that `https://github.com/segmentio/analytics-go` is in maintenance mode.

**Comment by zerospiel** [comment]
It has already been discussed with the team, and we've decided on the current implementation. @a13x5 @Kshatrix could you also check it once and if the current approach is ok — please close the issue

**Comment by s3rj1k** [comment]
> decided on the current implementation
empty token value was decided to be used?

**Comment by zerospiel** [comment]
It is not empty, please be advised about the [release CI](https://github.com/Mirantis/hmc/blob/b6de248602471d0ef1b1e0d7d9a6875658f04dec/.github/workflows/release.yml#L35).

**Comment by s3rj1k** [comment]
Makes sense, closing
